feat(ci): optimize build workflows and add ccache support
- add ccache support for all platforms
- simplify mingw package installation on windows
- remove redundant gpgme builds on linux
- add gpg signature verification for gnupg downloads
- improve artifact naming and organization
- link gpgme into core binary
- add portable mode configuration file
- optimize cmake configurations and build flags

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -60,6 +60,11 @@ jobs:
           lfs: "false"
           submodules: recursive
 
+      - name: ccache
+        uses: hendrikmuhs/ccache-action@v1.2
+        with:
+          key: release-${{ github.job }}-${{ matrix.os }}
+
       - name: Get Short SHA of Commit
         id: vars
         run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
@@ -105,80 +110,78 @@ jobs:
 
       - name: Install Dependence (macOS)
         run: |
-          brew install cmake autoconf automake texinfo gettext openssl@3
-          brew install ninja libarchive gpgme googletest
-          brew install create-dmg
-          brew link openssl@3 --force
+          brew install --formula cmake automake texinfo libarchive googletest create-dmg
         if: runner.os == 'macOS'
 
       - name: Set up MinGW (Windows)
         uses: msys2/setup-msys2@v2
+        id: msys2
         with:
           update: false
           release: false
           cache: true
           install: >-
-            git 
-            msys2-devel 
-            base-devel 
-            binutils 
+            git
             zip
             unzip
-            libintl
-            texinfo 
-            msys2-runtime-devel 
-            mingw-w64-x86_64-toolchain
-            mingw-w64-x86_64-gcc 
+            msys2-devel
+            base-devel
+            msys2-runtime-devel
+            mingw-w64-x86_64-gcc
             mingw-w64-x86_64-make
             mingw-w64-x86_64-cmake
-            mingw-w64-x86_64-qt6 
-            mingw-w64-x86_64-icu 
-            mingw-w64-x86_64-ninja 
-            mingw-w64-x86_64-gnupg 
-            mingw-w64-x86_64-gpgme
+            mingw-w64-x86_64-qt6-base
+            mingw-w64-x86_64-qt6-tools
+            mingw-w64-x86_64-ninja
             mingw-w64-x86_64-libarchive
             mingw-w64-x86_64-gtest
             mingw-w64-x86_64-autotools
+            mingw-w64-x86_64-texinfo
+            mingw-w64-x86_64-libassuan
+            mingw-w64-x86_64-ccache
         if: runner.os == 'Windows'
 
-      - name: Build gpg-error (Linux)
+      - name: Build GpgME (macOS)
         run: |
-          git clone --depth 1 --branch libgpg-error-1.51 git://git.gnupg.org/libgpg-error.git ${{github.workspace}}/third_party/libgpg-error
-          cd  ${{github.workspace}}/third_party/libgpg-error
-          ./autogen.sh
-          ./configure --enable-maintainer-mode && make -j4
-          sudo make install
-          cd ${{github.workspace}}
-        if: runner.os == 'Linux'
-
-      - name: Build assuan (Linux)
-        run: |
-          git clone --depth 1 --branch libassuan-2.5.7 git://git.gnupg.org/libassuan.git ${{github.workspace}}/third_party/libassuan
-          cd ${{github.workspace}}/third_party/libassuan
-          ./autogen.sh
-          ./configure --enable-maintainer-mode && make -j4
-          sudo make install
-          cd ${{github.workspace}}
-        if: runner.os == 'Linux'
-
-      - name: Build GpgME (Linux)
-        run: |
-          git clone --depth 1 --branch gpgme-1.24.2 git://git.gnupg.org/gpgme.git ${{github.workspace}}/third_party/gpgme
           cd ${{github.workspace}}/third_party/gpgme
+          export CC="ccache gcc"
+          export CXX="ccache g++"
           ./autogen.sh
-          ./configure --enable-maintainer-mode --enable-languages=cpp && make -j4
+          mkdir build && cd build
+          ../configure --enable-static \
+          --disable-shared \
+          --enable-silent-rules \
+          --disable-dependency-tracking \
+          --enable-languages=cl \
+          --disable-gpgconf-test \
+          --disable-gpg-test \
+          --disable-gpgsm-test \
+          --disable-g13-test
+          make -j4
           sudo make install
-          cd ${{github.workspace}}
-        if: runner.os == 'Linux'
+        if: runner.os == 'macOS'
 
       - name: Build GpgME (Windows)
         shell: msys2 {0}
         run: |
-          git clone --depth 1 --branch gpgme-1.24.2 git://git.gnupg.org/gpgme.git ${{github.workspace}}/third_party/gpgme
-          cd ${{github.workspace}}/third_party/gpgme
-          ./autogen.sh
+          cd $(cygpath -u "${{github.workspace}}")
+          cd third_party/gpgme
+          export CC="ccache gcc"
+          export CXX="ccache g++"
           export CFLAGS="${CFLAGS} -Wno-int-conversion -Wno-incompatible-pointer-types"
-          ./configure --enable-maintainer-mode --enable-languages=cl --disable-gpg-test --enable-w32-glib
+          ./autogen.sh
+          mkdir build && cd build
+          ../configure --enable-maintainer-mode \
+          --enable-static \
+          --disable-shared \
+          --enable-silent-rules \
+          --disable-dependency-tracking \
+          --enable-languages=cl \
+          --disable-gpgconf-test \
+          --disable-gpg-test \
+          --disable-gpgsm-test \
+          --disable-g13-test \
+          --enable-w32-glib
           make -j4
           make install
         if: runner.os == 'Windows'
@@ -188,26 +191,23 @@ jobs:
           git clone --depth 1 --branch v1.15.2 https://github.com/google/googletest.git ${{github.workspace}}/third_party/googletest
           cd ${{github.workspace}}/third_party/googletest
           mkdir build && cd build
-          cmake -G Ninja -DBUILD_SHARED_LIBS=ON ..
+          cmake -G Ninja -DBUILD_SHARED_LIBS=ON \
+            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
+            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
+            ..
           ninja
           sudo ninja install
         if: runner.os == 'Linux'
 
-      - name: Build & Install Full SDK
-        run: |
-          cmake -B ${{github.workspace}}/build-full-sdk -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGPGFRONTEND_BUILD_TYPE_FULL_SDK=ON
-          cmake --build ${{github.workspace}}/build-full-sdk --config {{$env.BUILD_TYPE}} -- -v
-          sudo cmake --install ${{github.workspace}}/build-full-sdk --config {{$env.BUILD_TYPE}}
-        if: runner.os == 'Linux' || runner.os == 'macOS'
-
       - name: Build GpgFrontend (macOS)
         run: |
           cmake -B ${{github.workspace}}/build -G Xcode \
-           -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
-           -DGPGFRONTEND_XCODE_CODE_SIGN_IDENTITY="${{secrets.GPGFRONTEND_XOCDE_CODE_SIGN_IDENTITY}}" \
-           -DGPGFRONTEND_XCODE_TEAM_ID="${{secrets.GPGFRONTEND_XCODE_TEAM_ID}}" \
-           -DGPGFRONTEND_XCODE_APPID="${{secrets.GPGFRONTEND_XOCDE_APPID}}" \
-           -DGPGFRONTEND_XCODE_PROVISIONING_PROFILE_UUID="${{secrets.GPGFRONTEND_XOCDE_PROVISIONING_PROFILE_UUID}}"
+            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
+            -DGPGFRONTEND_XCODE_CODE_SIGN_IDENTITY="${{secrets.GPGFRONTEND_XOCDE_CODE_SIGN_IDENTITY}}" \
+            -DGPGFRONTEND_XCODE_TEAM_ID="${{secrets.GPGFRONTEND_XCODE_TEAM_ID}}" \
+            -DGPGFRONTEND_XCODE_APPID="${{secrets.GPGFRONTEND_XOCDE_APPID}}" \
+            -DGPGFRONTEND_XCODE_PROVISIONING_PROFILE_UUID="${{secrets.GPGFRONTEND_XOCDE_PROVISIONING_PROFILE_UUID}}" \
+            -DGPGFRONTEND_LINK_GPGME_INTO_CORE=ON
           xcodebuild -list -project ${{github.workspace}}/build/GpgFrontend.xcodeproj
           cd ${{github.workspace}}/build/
           xcodebuild -scheme GpgFrontend -configuration "${{env.BUILD_TYPE}}"\
@@ -231,11 +231,11 @@ jobs:
           hdiutil create ${{github.workspace}}/build/tmp.dmg -ov \
             -volname "GpgFrontend" -fs HFS+ -srcfolder ${{github.workspace}}/build/package/
           mkdir ${{github.workspace}}/build/upload-artifact
-          create-dmg --codesign "${{secrets.GPGFRONTEND_XCODE_CODE_SIGN_IDENTITY}}" --volicon "${{github.workspace}}/resource/lfs/icns/GpgFrontend.icns" --volname GpgFrontend --app-drop-link 600 185 --window-size 800 400 ${{github.workspace}}/build/upload-artifact/GpgFrontend.dmg ${{github.workspace}}/build/package/GpgFrontend.app
+          create-dmg --codesign "${{secrets.GPGFRONTEND_XOCDE_CODE_SIGN_IDENTITY}}" --volicon "${{github.workspace}}/resource/lfs/icns/GpgFrontend.icns" --volname GpgFrontend --app-drop-link 600 185 --window-size 800 400 ${{github.workspace}}/build/upload-artifact/GpgFrontend.dmg ${{github.workspace}}/build/package/GpgFrontend.app
           mv ${{github.workspace}}/build/upload-artifact/GpgFrontend.dmg \
-            ${{github.workspace}}/build/upload-artifact/GpgFrontend-${{matrix.os}}-${{env.sha_short}}-x86_64.dmg
+            ${{github.workspace}}/build/upload-artifact/GpgFrontend-${{matrix.os}}-${{env.sha_short}}.dmg
           mv ${{github.workspace}}/build/GpgFrontend.app.zip \
-            ${{github.workspace}}/build/GpgFrontend-${{matrix.os}}-${{env.sha_short}}-x86_64.zip
+            ${{github.workspace}}/build/GpgFrontend-${{matrix.os}}-${{env.sha_short}}.zip
         if: runner.os == 'macOS'
 
       - name: Notarize Release Build (macOS)
@@ -244,14 +244,17 @@ jobs:
           --apple-id ${{secrets.APPLE_DEVELOPER_ID}} \
           --team-id ${{secrets.APPLE_DEVELOPER_TEAM_ID}} \
           --password ${{secrets.APPLE_DEVELOPER_ID_SECRET}} \
-          ${{github.workspace}}/build/GpgFrontend-${{matrix.os}}-${{env.sha_short}}-x86_64.zip
+          ${{github.workspace}}/build/GpgFrontend-${{matrix.os}}-${{env.sha_short}}.zip
           echo "BUILD_TYPE_LOWER=$(echo ${BUILD_TYPE} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
           echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> ${GITHUB_ENV}
         if: runner.os == 'macOS'
 
       - name: Build GpgFrontend (Linux)
         run: |
-          cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGPGFRONTEND_BUILD_APP_IMAGE=ON
+          cmake -B ${{github.workspace}}/build -G Ninja \
+            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
+            -DGPGFRONTEND_BUILD_APP_IMAGE=ON \
+            -DGPGFRONTEND_LINK_GPGME_INTO_CORE=ON
           cmake --build ${{github.workspace}}/build --config {{$env.BUILD_TYPE}} -- -v
         if: runner.os == 'Linux'
 
@@ -262,7 +265,12 @@ jobs:
           wget -c -nv https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
           chmod u+x linuxdeployqt-continuous-x86_64.AppImage
           export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
-          ./linuxdeployqt-continuous-x86_64.AppImage ${{github.workspace}}/build/artifacts/AppDir/usr/share/applications/*.desktop -no-translations -extra-plugins=iconengines,platforms,wayland-graphics-integration-client,wayland-decoration-client,wayland-shell-integration -appimage -executable-dir=${{github.workspace}}/build/artifacts/AppDir/usr/lib/modules
+          ./linuxdeployqt-continuous-x86_64.AppImage \
+            ${{github.workspace}}/build/artifacts/AppDir/usr/share/applications/*.desktop \
+            -no-translations \
+            -extra-plugins=iconengines,platforms \
+            -appimage \
+            -executable-dir=${{github.workspace}}/build/artifacts/AppDir/usr/lib/modules
           echo "BUILD_TYPE_LOWER=${BUILD_TYPE,,}" >> ${GITHUB_ENV}
           echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> ${GITHUB_ENV}
         if: runner.os == 'Linux'
@@ -272,7 +280,10 @@ jobs:
         run: |
           cd $(cygpath -u "${{github.workspace}}")
           mkdir build && cd build
-          cmake -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
+          cmake -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
+            -DGPGFRONTEND_SIGN_BUILT_BINARY=ON \
+            -DGPGFRONTEND_LINK_GPGME_INTO_CORE=ON \
+            ..
           cmake --build . --config ${{env.BUILD_TYPE}}  -- -j 4
         if: runner.os == 'Windows'
 
@@ -286,14 +297,27 @@ jobs:
         shell: msys2 {0}
         run: |
           export URL="https://ftp.bktus.com/GnuPG/${{env.GNUPG_VERSION}}"
+          export KEY_URL="https://ftp.bktus.com/GPG_KEYS/5CA3DA246843FD03.asc"
           export FILE="gnupg.zip"
           export CHECKSUM_FILE="SHA256SUMS.txt"
+          export SIGNATURE_FILE="gnupg.zip.sig"
+          export GNUPGHOME=$(mktemp -d)
 
           cd $(cygpath -u "${{github.workspace}}")
 
           mkdir -p build/downloads
+
           curl -o build/downloads/$FILE $URL/$FILE
           curl -o build/downloads/$CHECKSUM_FILE $URL/$CHECKSUM_FILE
+          curl -o build/downloads/5CA3DA246843FD03.asc $KEY_URL
+          curl -o build/downloads/$SIGNATURE_FILE $URL/$SIGNATURE_FILE
+
+          gpg --import build/downloads/5CA3DA246843FD03.asc
+          gpg --verify build/downloads/$SIGNATURE_FILE build/downloads/$FILE
+          if [ $? -ne 0 ]; then
+            echo "GnuPG signature verification failed!" >&2
+            exit 1
+          fi
 
           CHECKSUM=$(grep "$FILE" build/downloads/$CHECKSUM_FILE | awk '{print $1}')
           ACTUAL_CHECKSUM=$(sha256sum build/downloads/$FILE | awk '{print $1}')
@@ -322,15 +346,19 @@ jobs:
           rm -rf build/artifacts/bin/*.a
           rm -rf build/artifacts/bin/modules/*.a
           mv build/artifacts/bin/modules build/artifacts/modules
-          touch build/artifacts/bin/PORTABLE.txt
+          touch build/artifacts/bin/ENV.ini
+          echo "PortableMode=true" >> build/artifacts/bin/ENV.ini
           cd build
           windeployqt-qt6 --no-translations --force ./artifacts/bin/libgf_core.dll
           windeployqt-qt6 --no-translations --force ./artifacts/bin/libgf_ui.dll
           windeployqt-qt6 --no-translations --force ./artifacts/bin/libgf_test.dll
           windeployqt-qt6 --no-translations --force ./artifacts/bin/GpgFrontend.exe
+          for module in ./artifacts/modules/*.dll; do
+            windeployqt-qt6 --no-translations --force "$module"
+          done
           mkdir upload-artifact
           cd artifacts
-          zip -r ../upload-artifact/GpgFrontend-${{env.SHORT_SHA}}-x86_64.zip *
+          zip -r ../upload-artifact/GpgFrontend-${{env.SHORT_SHA}}-${{matrix.os}}-x86_64.zip *
         if: runner.os == 'Windows'
 
       - name: Upload Artifact (Linux)
@@ -351,5 +379,5 @@ jobs:
         uses: actions/upload-artifact@master
         with:
           name: gpgfrontend-${{matrix.os}}-${{env.BUILD_TYPE_LOWER}}-${{env.SHORT_SHA}}
-          path: ${{github.workspace}}/build/artifacts/*
+          path: ${{github.workspace}}/build/upload-artifact/*
         if: runner.os == 'Windows'
